libgps.h: Fix linkage problem
When building with libQgpsmm=1 enabled I see this failure:

g++ -o libgps_core-qt.os -c -D_GNU_SOURCE -Wextra -Wall -Wno-uninitialized -Wno-missing-field-initializers -Wcast-align -Wmissing-declarations -Wmissing-prototypes -Wpointer-arith -Wreturn-type -pthread -Wmissing-declarations -O2 -pthread -fPIC -DUSE_QT -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtCore libgps_core.c
cc1plus: warning: command line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
In file included from libgps_core.c:19:0:
gps_json.h:41:28: error: conflicting declaration of 'int json_ais_read(const char*, char*, size_t, ais_t*, const char**)' with 'C' linkage
     /*@null@*/const char **);
                            ^
In file included from libgps_core.c:18:0:
libgps.h:34:12: note: previous declaration with 'C++' linkage
 extern int json_ais_read(const char *, char *, size_t, struct ais_t *,
            ^
scons: *** [libgps_core-qt.os] Error 1
scons: building terminated because of errors.

Digging more into the problem shows, libgps.h doesn't have the
functions enclosed within 'extern "C"' mark. Therefore, g++ mangled
the function names and hence the error.

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Signed-off-by: Jon Schlueter <jon.schlueter@gmail.com>